version: '3'

services:
  client:
    build: 
      context: ./apps/client
      args:
        VITE_API_ENDPOINT_URL: ${CLIENT_API_ENDPOINT_URL}
    container_name: client
    networks:
      - task-todo-app

  server:
    build: ./apps/server
    container_name: server
    depends_on:
      - database
    environment:
      - LISTEN_PORT=3000
      - MONGODB_URL=${SERVER_MONGODB_URL}
    networks:
      - task-todo-app

  database:
    image: mongo:7.0.11
    container_name: database
    networks:
      - task-todo-app
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    depends_on:
      - client
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - task-todo-app

networks:
  task-todo-app:
    driver: bridge

volumes:
  mongodb_data: